race_car:
  ros__parameters:
    reference_frame: "track"
    robot_frame: "base_footprint"
    update_rate: 1000.0
    publish_rate: 200.0
    control_delay: 0.035
    steering_lock_time: 1.5

sbg_driver:
  ros__parameters:
    reference_frame: "track"
    robot_frame: "base_footprint"
    ekf_update_rate: 50.0
    gps_update_rate: 5.0
    vel_update_rate: 200.0

# cone_detection:
#   ros__parameters:
    