#!/usr/bin/env python3.8

import sys

from eufs_tracks.converter_tool import EUFSConverterGUI
from rqt_gui.main import Main

plugin = 'eufs_tracks.converter_tool.EUFSConverterGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
