#!/usr/bin/env python3.8

import sys

from eufs_tracks.track_generator import EUFSTracksGUI
from rqt_gui.main import Main

plugin = 'eufs_tracks.track_generator.EUFSTracksGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
