#!/usr/bin/env python

import sys

from ros_can_sim import EUFSRobotSteeringGUI
from rqt_gui.main import Main

plugin = 'eufs_robot_steering_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
