#!/usr/bin/env python

import sys

from eufs_rqt.EUFSRobotSteeringGUI import EUFSRobotSteeringGUI
from rqt_gui.main import Main

plugin = 'eufs_rqt.EUFSRobotSteeringGUI.EUFSRobotSteeringGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
