#!/usr/bin/env python

import sys

from rqt_gui.main import Main

from eufs_rqt.MissionControlGUI import MissionControlGUI

plugin = "eufs_rqt.MissionControlGUI.MissionControlGUI"
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
