#!/usr/bin/env python

import sys

from ros_can_sim.RosCanSimGUI import RosCanSimGUI
from rqt_gui.main import Main

plugin = 'ros_can_sim.RosCanSimGUI.RosCanGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
