#!/usr/bin/env python3.8

import sys

from eufs_launcher.LauncherModule import EufsLauncher
from rqt_gui.main import Main

plugin = 'eufs_launcher.LauncherModule.EufsLauncher'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
