inertia:
  m:        235     # Weight of the Vehicle [kg]
  g:        9.81    # Gravity force         [m/s^2]
  I_z:      31.27   # Inertial force I_zz   [kg/m^2]

kinematics:
  l: 1.525          # Wheelbase              [m]
  # COG is estimated to be 300mm back from cnetre of rotation
  b_F: 1.0        # From COG to front axle [m]
  b_R: 0.525        # From COG to rear axle  [m]
  w_front: 0.45     # Percentage of weight front
  axle_width: 1.4

tire:
  tire_coefficient: 1.0
  B: 12.56
  C: -1.38
  D: 1.60
  E: -0.58
  radius: 0.2032

aero:
  C_Down: 3.22455 # F_Downforce = C_Downforce*v_x^2
  C_drag: 1.44475  # F_Drag = C_Drag*v_x^2

input_ranges:
  acceleration:
    max: 3
    min: -10
  velocity:
    max: 30
    min: 0
  steering:
    max: 0.28
    min: -0.28
