/**: # global parameters
  ros__parameters:
    reference_frame: "track"
    robot_frame: "base_footprint"
    # params rewritten by launcher upon user selection:
    noise_config: "null"
    publish_ground_truth: false
    publish_transform: false
    simulate_perception: false
    simulate_slam: false

gazebo:
  ros__parameters:
    # default is 10.0. we needed higher freq so the gazebo clock would update faster.
    # this was responsible for calculating time deltas in other node processes.
    publish_rate: 100.0

race_car:
  ros__parameters:
    update_rate: 1000.0
    publish_rate: 200.0
    control_delay: 0.035
    steering_lock_time: 1.5
    # params rewritten by launcher upon user selection:
    command_mode: "velocity"
    vehicle_config: "null"
    vehicle_model: "DynamicBicycle"

sbg_driver:
  ros__parameters:
    ekf_update_rate: 50.0
    gps_update_rate: 5.0
    vel_update_rate: 200.0

cone_detection:
  ros__parameters:
    gt_update_rate: 50.0
    lidar_update_rate: 10.0
    lidar_frame_id: "velodyne"
    lidar_min_view_distance: 1.0
    lidar_max_view_distance: 20.0
    lidar_fov: 3.141593 # 180 degrees
    lidar_range_noise: 0.01
    lidar_bearing_noise: 0.001
    lidar_detects_colour: false
    lidar_offset_x: 1.59
    camera_update_rate: 15.0
    camera_frame_id: "zed2i_left_camera_optical_frame"
    camera_min_view_distance: 0.5
    camera_max_view_distance: 10.0
    camera_fov: 1.91986 # 110 degrees
    camera_range_noise: 0.01
    camera_bearing_noise: 0.01
    camera_detects_colour: true
    camera_offset_x: -0.37
    slam_update_rate: 20.0
    slam_frame_id: "track"
    slam_x_noise: 0.1
    slam_y_noise: 0.1
    slam_local_frame_id: "base_footprint"
    slam_local_range_x: 20.0
    slam_local_range_y: 10.0
